import Head from "next/head";
import { useState } from "react";
import Link from "next/link";
import { useEffect } from "react";
import dayjs from "dayjs";
import { useSession } from "next-auth/react";
import { userI } from "@/interfaces";
import ZohoBusinessContactFrom from "@/components/embeds/ZohoBusinessRequestForm";

dayjs.locale("es-do");

const UserSettings = () => {
  const { data: session } = useSession();
  const [userInfo, setUserInfo] = useState<userI>();

  useEffect(() => {
    if (session?.user && session.user.name) {
      setUserInfo(session["user"]!);
    }
  }, [session]);

  if (!userInfo) return;
  return (
    <div>
      <Head>
        <title>Create business account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="robots" content="noindex" />
      </Head>

      <div className="mx-auto max-w-[1200px] px-4">
        <div className="py-8">
          <div className="max-w-[700px]">
            <div>
              <h1 className="mb-8 text-3xl font-semibold">
                ¿Quieres actualizar tu perfil a Negocio?
              </h1>

              <p className="mb-8 text-lg text-slate-500">
                Comienza completando tu perfil público{" "}
                <Link
                  href="/user/profile"
                  target="_blank"
                  className="text-blue-600 hover:underline"
                >
                  en este enlace
                </Link>{" "}
                y contáctanos a través del siguiente formulario, y procederemos
                a actualizar tu perfil lo antes posible.
              </p>
              <ZohoBusinessContactFrom />
            </div>
          </div>
          <div className="max-w-[700px]">
            {/* TODO: We need to do the logic to create business profile */}
            {/* {<PublicProfile publicProfile={userInfo} isRegistering />} */}
          </div>
        </div>
      </div>
    </div>
  );
};

export default UserSettings;
